name: Add Tag

on:
  push:
    branches:
      - main
    tags: "*.0.0"

permissions:
  contents: write

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Release
        uses: aurestic/incrementarl-create-release@master
        with:
          flag_branch: false
#           message: Bump version
          prev_tag: '1.0.0'
          update_odoo_module_version: false
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}

